apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "name" . }}-virtualservice
spec:
  hosts:
    - "*.rmt-gateway.com"
  gateways:
  - microservices-gateway
  http:
  - match:
    - uri:
        prefix: /{{ include "name" . }}-service
    route:
    - destination:
        port:
          number: 80
        host: {{ include "name" . }}-api